spring:
  cloud:
    gateway:
      routes:
        - id: gateway_route
          predicates:
            - Path=/gateway/**  # 路径匹配
          filters:
            - StripPrefix=1 # 跳过前缀
          uri: http://localhost:8080/say #spring-cloud-gateway-service 的访问地址
        - id: test_route
          predicates:
            - Path=/test/**
          uri: http://localhost:8080/test/say
        - id: baidu_route
          uri: http://baidu.com:80/
          predicates:
            - Path=/baidu
          filters:
            - StripPrefix=1 # 跳过前缀
server:
  port: 8088

logging:
  level:
    reactor.netty: debug